# 应用服务 WEB 访问端口
server:
  port: 8081
# 应用名称
spring:
  application:
    name: eureka-client

eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  instance:
    #服务名称修改
    instance-id: payment8081
    #访问路径可以显示ip地址
    prefer-ip-address: true

