server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: false
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762/eureka
